/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

import javax.swing.JFrame;

public class main {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame window = new JFrame();
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//close on x button
        window.setResizable(false);//panel can't be resized
        window.setTitle("2D Adventure");
        GamePanel gamePanel = new GamePanel();
        
        window.add(gamePanel);
// add a component, in this case class GamePanel
        window.pack();
//caused the window to be sized to fit the preffered size (=GamePanel)
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        
        gamePanel.startGameThread();
        
    }
}
