/*
 * This source file was generated by the Gradle 'init' task
 */
package main;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
       mainp classUnderTest = new mainp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private static class mainp {

        public mainp() {
        }

        private Object getGreeting() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
